
spring:
  main:
    show_banner: true
    web_environment: true  
  application:
    name: oauth2-demo

server:
  port: 8081

#Logging
logging:
  level:
    ROOT: ERROR
    com.saas: INFO


security:
  user:
    name: test
    password: test123
  oauth2:
    client:
      clientId: apiman
      clientSecret:
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
    resource:
      user-info-uri: http://127.0.0.1:8080/auth/realms/demo/protocol/openid-connect/userinfo
      
      
